# Generated by Django 5.1.1 on 2024-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_storage',
            field=models.PositiveIntegerField(default=0, verbose_name='used storage'),
        ),
    ]
